const languages = [

    {
        code: 0,
        lang: "English",
        short: "En",
        img: "",
        dict: {
            RUNNING: "Running Simulation",
            NUMBER_OF_IMAGE: "Number of Images",
            IN_PROGRESS: "In Progress",
            HISTOGRAM: "Histogram",
            SHOW: "Show",
            lOAD_IMAGE: "load image",
            NUC: "NUC",
            ENABLE: "Enable",
            METHOD: "Method",
            PT1: "1pt",
            PT2: "2pt",
            BED_pIXCEL_COORECTION: "Bed Pixel Coorection",
            SENSOR_CHARACTERISICS: "Sensor Characterisics File",
            DYNAMIC_RANGE_STRECH: "Dynamic Range Strech",
            METHOD: "Method",
            PRECENT: "precent",
            BRING_DISCARD_PERCENTILE: "Bring Discard Percentile",
            DARK_DISCARD_PERCENTILE: "Dark Discard Percentile",
            METHOD: "Newton",
            PIXEL_ORDER: "hrfv",
            DEMOSIC: "Demosic",
            METHOD: "",
            RADIUS: "",
            ESP: "",
            SHARPING: "Sharping",
            TREHOLD: "Trehold",
            RUNISP: "Run ISP",
            HISTORY_SORT: "Sort by",
            HISTORY_SORT_ASC: "Sort by date ASC",
            HISTORY_SORT_DESC: "Sort by date DESC",
            HISTORY_SORT_NAME: "Sort by name",
            HISTORY_SEARCH: "search",
            CHANGEFRAME_START: "Start Frame",
            CHANGEFRAME_END: "End Frame",
            CAROUSEL_SELECTED_IMAGE: "Selected Image",
            CAROUSEL_LOAD_IMAGE: "Please Load Image",
            DELETE_IMAGE_FROM_HISTORY: "delete",
            VIEW_PDF: "view pdf",
            DOWNLOAD_FROM_HISTORY: "download",
            CREATION: "creation",
            SEND: "send",
            NEW_ACCOUNT: "New Account",
            SIGN_IN: "Sign In",
            NEW_ACCOUNT: "new account",
            TITLE_FORGOT_PASSWORD: "Forgot Password ?",
            FORGOT_PASSWORD: "forgot password",
            TITLE_NEW_ACCOUNT: "New Account",
            MSG_GIVE_EMAIL_REGISTER: "Just tell us the email address you would like to register with us",
            MSG_GIVE_EMAIL_REGISTER: "Just tell us the email address you registered width us",
            TITLE_FORGOT_PASSWORD: "Forgot Password ?",
            PASSPORD: "Passpord",
            CHENG: "Cheng",
            CREATE: "Create",
            MINIMUM_SO_VALUE: "Minimun S0 value",
            MAXIMUM_SO_VALUE: "Maximum S0 value",
            DOLP: "Dolp",
            DOLP_MINIMUM: "DoLP Minimum",
            DOLP_MAXIMUM: "DoLP Maximum",
            ALOP_OVERLAYED: "AoLP Overlayed",
            HUE_SCALE_FACTOR: "Hue Scale Factor",
            AOLPDOLP: "AoLP+DoLP",
            DOLP_SSTUTATION: "DoLP Satutation",
            ALOPֹ_BRIGHNTESS_CONTROL: "AoLP brighntess control",
            RGB: "RGB",
            ALOP_CENTER: "AoLP Center",
            ALOP_FOV: "AoLP FOV",
            MINIMUM_DOLP_VALUE: "Minimum DoLP value",
            MAXIMUM_DOLP_VALUE: "Maximum DoLP value",
            DISPLAY_SETTING: "Display settings",
            SAVE_RESULTS: "Save Results",


        }
    }
]

export default languages[0].dict;
